services:
  db:
    image: mariadb:latest
    container_name: carrito_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: carrito_db
      MYSQL_USER: usuario_carrito
      MYSQL_PASSWORD: contrasena_carrito
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
    container_name: carrito_django
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done;
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True

volumes:
  db_data: