# Generated by Django 5.2.1 on 2025-06-01 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito de Compras',
                'verbose_name_plural': 'Carritos de Compras',
                'db_table': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='HistorialCarrito',
            fields=[
                ('id_historial_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='carrito.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Carrito',
                'verbose_name_plural': 'Historial de Carritos',
                'db_table': 'Historial_Carritos',
            },
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'verbose_name_plural': 'Productos en Carrito',
                'db_table': 'Carrito_Productos',
                'unique_together': {('carrito', 'producto')},
            },
        ),
    ]
