# Generated by Django 5.2.1 on 2025-06-07 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='carrito.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación a Carrito',
                'verbose_name_plural': 'Invitaciones a Carrito',
                'db_table': 'Invitaciones_Carrito',
                'unique_together': {('carrito', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuarios_compartidos',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que tienen acceso a este carrito', related_name='carritos_compartidos', through='carrito.InvitacionCarrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
