# Generated by Django 5.2.1 on 2025-06-07 08:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_invitacioncarrito_carrito_usuarios_compartidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuarios_compartidos',
            field=models.ManyToManyField(blank=True, related_name='carritos_compartidos', through='carrito.InvitacionCarrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
