# Generated by Django 5.2.1 on 2025-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carrito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
