# Generated by Django 5.2.3 on 2025-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_carritoproducto_supermercado_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
