# Generated by Django 5.2.3 on 2025-06-12 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_alter_carritoproducto_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoActivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_por_usuario', to='carrito.carrito')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_activo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito Activo por Usuario',
                'verbose_name_plural': 'Carritos Activos por Usuario',
                'db_table': 'Carrito_Activo_Usuario',
                'unique_together': {('usuario',)},
            },
        ),
    ]
