# Generated by Django 5.2.1 on 2025-05-11 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLegacy',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
