# Generated by Django 5.2.1 on 2025-06-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id_supermercado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('geolocalizacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Supermercados',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.producto')),
                ('id_supermercado', models.ForeignKey(db_column='id_supermercado', on_delete=django.db.models.deletion.CASCADE, to='productos.supermercado')),
            ],
            options={
                'db_table': 'Precios',
                'unique_together': {('id_producto', 'id_supermercado')},
            },
        ),
    ]
