# Generated by Django 5.2.2 on 2025-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='precio',
            unique_together={('id_producto', 'id_supermercado', 'fecha_actualizacion')},
        ),
    ]
