# Generated by Django 5.2.2 on 2025-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_precio_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
