name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: carrito_db
          MYSQL_USER: usuario_carrito
          MYSQL_PASSWORD: contrasena_carrito
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for DB to be ready
      run: |
        until nc -z localhost 3306; do
          echo "Waiting for the database...";
          sleep 1;
        done

    - name: Run migrations
      env:
        DATABASE_URL: mysql://usuario_carrito:contrasena_carrito@localhost:3306/carrito_db
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: mysql://usuario_carrito:contrasena_carrito@localhost:3306/carrito_db
      run: |
        python manage.py test