name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: carrito_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h127.0.0.1 -uroot -proot_password"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=40s

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-mysql-client
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for DB to be ready
      run: |
        for i in {1..30}; do
          if mysql -h127.0.0.1 -uroot -proot_password -e "SELECT 1;" &>/dev/null; then
            echo "Database is ready!";
            break;
          fi
          echo "Waiting for the database... (Attempt $i of 30)";
          sleep 5;
        done

    - name: Run migrations
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root_password
        DB_NAME: carrito_db
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root_password
        DB_NAME: carrito_db
      run: |
        python manage.py test --noinput