name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: carrito_db
          MYSQL_USER: usuario_carrito
          MYSQL_PASSWORD: contrasena_carrito
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uusuario_carrito -pcontrasena_carrito || exit 1"
          --health-interval=10s
          --health-timeout=20s
          --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10-slim

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for DB to be ready
      run: |
        for i in {1..20}; do
          if mysqladmin ping -h 127.0.0.1 -uusuario_carrito -pcontrasena_carrito --silent; then
            echo "Database is ready!";
            break;
          fi
          echo "Waiting for the database...";
          sleep 5;
        done

    - name: Run migrations
      env:
        DATABASE_URL: mysql://usuario_carrito:contrasena_carrito@localhost:3306/carrito_db
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: mysql://usuario_carrito:contrasena_carrito@localhost:3306/carrito_db
      run: |
        python manage.py test