name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: carrito_db
          MYSQL_USER: usuario_carrito
          MYSQL_PASSWORD: contrasena_carrito
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h db -uusuario_carrito -pcontrasena_carrito"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Clean up Docker resources
      run: |
        docker rm -f $(docker ps -aq) || true
        docker network prune -f || true

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-mysql-client
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for DB to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h db -uusuario_carrito -pcontrasena_carrito &>/dev/null; then
            echo "Database is ready!";
            break;
          fi
          echo "Waiting for the database... (Attempt $i of 30)";
          sleep 5;
        done

    - name: Print MariaDB logs
      run: |
        docker logs $(docker ps -q --filter "ancestor=mariadb:10.5") || echo "No logs available"

    - name: Run migrations
      env:
        DB_HOST: db
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DB_HOST: db
      run: |
        python manage.py test